### ISSUE TITLE
How is this file structured?

### ISSUE THREAD

**Issue by sdondley** [carltonnorthern/nickname-and-diminutive-names-lookup#14]
I don't understand how this file is structured. If I want to find the name associated with "Dicky," how would I do that aside from looking through the file manually?
And why are some names spread across multiple lines? Shouldn't each name appear on only one line? Example:
```
russ,russell
russell,russ,rusty
rusty,russell
```
Shouldn't those closely associated names be on one line?

I tried the Perl script out but all it did was display how many names had more than 5 mentions in the file.

**Comment by carltonnorthern** [comment]
Unfortunately, the file isn't structured very well.  I'd say that column 1 should have the given name, and columns 2+ should be the diminutive and nicknames, but as your example makes clear this is not always the case.  I think the first and third lines should be removed and line two should remain.  I'm going to try and clean up some of these.
