### ISSUE TITLE
The JavaParser has the wrong type definition for the dimNames map

### ISSUE THREAD

**Issue by chrisco484** [carltonnorthern/nickname-and-diminutive-names-lookup#23]
Currently the map is declared with:

`public Map<String, String> dimNames = new HashMap<String, String>();`

but that won't compile because the code needs to store a map keyed on String but with a List of Strings being the value type. So this is the correct declaration:

`Map<String, List<String>> dimNames = new HashMap<>();`

Nice list - what is the best way for suggesting new aliases/nicknames?

**Comment by carltonnorthern** [comment]
Thanks!  I've been fairly hands-off with this project for a while.  A pull request for both this issue, and for suggesting additions would be great appreciated!
