### ISSUE TITLE
Make release on PyPI

### ISSUE THREAD

**Issue by NickCrews** [carltonnorthern/nickname-and-diminutive-names-lookup#33]
Hi! This looks to me to be one of the better maintained datasets of diminutive names on GitHub. It could be easier to use in python if this was actually released on PyPI so people could do a `pip install nicknames` (surprisingly this package name isn't taken? Could definitely choose another name too.)

If I open a PR for this, would you be open to it? I'd add a github action similar to [this one](https://github.com/dedupeio/dedupe/blob/master/.github/workflows/pythonpackage.yml#L60) that would build and release the wheels automatically on a git tag. Your admin overhead on a day-to-day would be minimal, you'd just have to set up an PyPI account and add the access token to this repo's Secrets once. I can help with this too if you want.

Thank you!

**Comment by carltonnorthern** [comment]
Yes!  This would be great.  Sorry for taking so long to respond.
