### ISSUE TITLE
Problems with names.csv

### ISSUE THREAD

**Issue by pengyu** [carltonnorthern/nickname-and-diminutive-names-lookup#6]
There are some problems with `names.csv`.

For example, Jon is the shortened form of Jonathan. But it is not mentioned in names.csv.

https://en.wikipedia.org/wiki/Jon

**Comment by leesharma** [comment]
I bet if you submitted a PR with that change, they would accept it.

From the README:

> Any help from people to clean this list up and add to it is greatly appreciated. Think of it as a wiki.

**Comment by carltonnorthern** [comment]
Yes, please consider contributing to the files with anything that is missing or any discrepancies.
